version: "3.5"

services:

  #php server
  canvasdk:
    image: mctekk/phalconphp:latest
    volumes:
      - .:/app
      - ../canvas-core:/canvas-core
      - ../../baka:/baka
    depends_on: 
      - 'redis'
    tty: true
    ports:
      - "9002:9000"
    networks:
      - local-network

  swoole:
    build: .
    volumes:
      - .:/app
      - ../canvas-core:/canvas-core
      - ../../baka:/baka
    depends_on:
      - 'redis'
    tty: true
    ports:
      - "8081:8081"
    networks:
      - local-network 

  nginx:
    image: nginx:latest
    ports:
        - "82:80"
    links:
        - canvasdk
    volumes:
        - .:/app
        - ./storage/ci/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-network
      - public-network

  redis:
    image: 'redis:5.0.5-alpine'
    ports: 
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - local-network

volumes:
  db-data:
  redis:
  esdata:
  rabbitsvolumns:

networks:
  local-network:
  public-network:
  canvasproxynet:
    name: canvas_network
