<?php

use Baka\Router\Route;

return [
    Route::crud('/users')->controller('ApiController')->action('privateTransporter')->notVia('post'),
    Route::crud('/companies')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/roles')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/locales')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/currencies')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/apps')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/notifications')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/system-modules')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/companies-branches')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/apps-plans')->controller('ApiController')->action('privateTransporter'),
    Route::post('/apps-plans/{id}/reactivate')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/roles-acceslist')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/permissions-resources')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/permissions-resources-access')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/users-invite')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/devices')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/languages')->controller('ApiController')->action('privateTransporter'),
    Route::crud('/webhooks')->controller('ApiController')->action('privateTransporter'),
    Route::get('/timezones')->controller('ApiController')->action('privateTransporter'),
    Route::post('/notifications-read-all')->controller('ApiController')->action('privateTransporter'),
    Route::post('/users/{id}/devices')->controller('ApiController')->action('privateTransporter'),
    Route::delete('/users/{id}/devices/{deviceId}')->controller('ApiController')->action('privateTransporter'),
    Route::delete('/filesystem/{id}/attributes/{name}')->controller('ApiController')->action('privateTransporter'),
    Route::put('/filesystem-entity/{id}')->controller('ApiController')->action('privateTransporter'),
    Route::put('/auth/logout')->controller('ApiController')->action('privateTransporter'),
    Route::post('/users/invite')->controller('ApiController')->action('privateTransporter'),
    Route::post('/roles-acceslist/{id}/copy')->controller('ApiController')->action('privateTransporter'),
    Route::get('/custom-fields-modules/{id}/fields')->controller('ApiController')->action('privateTransporter'),
    Route::put('/apps-plans/{id}/method')->controller('ApiController')->action('privateTransporter'),
    Route::get('/schema/{slug}')->controller('ApiController')->action('privateTransporter'),
    Route::get('/schema/{slug}/description')->controller('ApiController')->action('privateTransporter'),
    Route::post('/users/{hash}/change-email')->controller('ApiController')->action('privateTransporter'),
    Route::post('/users/{id}/request-email-change')->controller('ApiController')->action('privateTransporter'),
    Route::put('/users/{id}/apps/{appsId}/status')->controller('ApiController')->action('privateTransporter'),
    Route::get('/companies-groups')->controller('ApiController')->action('privateTransporter'),
    Route::get('/companies-groups/{id}')->controller('ApiController')->action('privateTransporter')
];
